---
- name: My test task - installing LEMP using docker-compose
  hosts: all
  vars:
    server_hostname: www.my-test-task.com
  tasks:
    - name: install packages
      yum: name={{ item }} state=latest update_cache=yes
      with_items:
        - git
        - wget
        - curl

    - name: Add Docker repo
      get_url:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/docker-ce.repo
      become: yes
 
    - name: Install Docker
      package:
        name: docker-ce
        state: latest
      become: yes
 
    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes
      become: yes
 
    - name: Add user to docker group
      user:
        name: user
        groups: docker
        append: yes
      become: yes

    - name: install docker-compose
      shell: sudo curl -L "https://github.com/docker/compose/releases/download/1.23.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose && sudo chmod +x /usr/local/bin/docker-compose

    - name: Start docker daemon
      service: name=docker state=started enabled=yes

    - name: Deploy site files from Github repository
      git: repo=https://github.com/AlexanderM33/LEMP-test.git dest=/home/user/docker-compose-lemp-stack update=yes force=yes

    - name: deploy Docker Compose stack
      community.docker.docker_compose_v2:
        project_src: /home/user/docker-compose-lemp-stack/docker-compose-LEMP/
        files:
        - docker-compose.yml
